import { validateConfig, createExam, startSection, chooseAnswer, advance, expire, submitSection, parseKey, formatTime, escapeHTML as e } from './core.js';
import { load, save, storageAvailable, rememberResult, savedResults } from './storage.js';
import { openPDF, preparePDF, pageImage, clearPages } from './pdf.js';
import { toolsMarkup, mountTools } from './tools.js';
import { reportMarkup, totals, copyContent, csvContent } from './report.js';
const app=document.querySelector('#app');
let exam=load('current'), config={title:'',sections:[{name:'언어이해',start:1,end:1,count:20,minutes:15,key:null}]};
let pdfInfo=null, fileName='', prepared=false, pageNumber=1, zoom=100, view='setup', busy=false, lastAction=0;
let library=load('keys',[]), selectedKey='', timer=null, resultFilter='all';
const lockName='skct-room-v1-active';
let releaseLock=null, locked=false;
async function acquireLock(){
  if(!navigator.locks) { locked=true; return; }
  await new Promise(resolve=>navigator.locks.request(lockName,{ifAvailable:true}, async lock=>{
    if(!lock){locked=false;resolve();return;}
    locked=true;resolve();await new Promise(r=>{releaseLock=r;});
  }));
}
await acquireLock();
if(!locked){app.innerHTML='<section class="panel empty-state"><h1>다른 창에서 시험장이 열려 있습니다.</h1><p>응시 기록 충돌을 막기 위해 한 창에서만 사용할 수 있습니다. 다른 창을 닫은 뒤 새로고침해 주세요.</p></section>';document.querySelectorAll('nav button').forEach(b=>b.disabled=true);}
else { if(exam?.phase==='running' && expire(exam))persist(); if(exam?.phase==='finished'){view='result';rememberResult(exam);renderResult();}else renderSetup(); }
function notify(text){const t=document.querySelector('#toast');t.textContent=text;t.hidden=false;clearTimeout(t._timeout);t._timeout=setTimeout(()=>t.hidden=true,4200);}
function persist(){const current=load('current');if(exam && !(current && current.id!==exam.id && ['ready','running','between'].includes(current.phase)))save('current',exam); document.querySelector('#storage-warning').hidden=storageAvailable();}
function nav(){document.querySelector('#nav-setup').classList.toggle('active',['setup','exam'].includes(view));document.querySelector('#nav-history').classList.toggle('active',['history','result'].includes(view));}
function currentConfig(){return {title:app.querySelector('#exam-title')?.value??config.title,sections:[...app.querySelectorAll('.subject-row')].map(row=>({name:row.querySelector('[name=name]').value,start:Number(row.querySelector('[name=start]').value),end:Number(row.querySelector('[name=end]').value),count:Number(row.querySelector('[name=count]').value),minutes:Number(row.querySelector('[name=minutes]').value),key:null}))};}
function applyLibrary(c){if(!selectedKey)return c;const key=library.find(k=>k.id===selectedKey);if(!key)throw new Error('선택한 정답표를 찾을 수 없습니다.');if(key.sections.length!==c.sections.length||key.sections.some((s,i)=>s.count!==c.sections[i].count))throw new Error('정답표의 과목 수·문항 수와 시험 설정이 다릅니다.');return {...c,sections:c.sections.map((s,i)=>({...s,key:key.sections[i].key}))};}
function subjectRow(s,i){return `<div class="subject-row"><span class="subject-index">${String(i+1).padStart(2,'0')}</span><label class="subject-name">과목 이름<input name="name" maxlength="40" value="${e(s.name)}" required></label><label>시작 페이지<input name="start" type="number" min="1" max="10000" value="${s.start}" required></label><span class="range-dash">—</span><label>끝 페이지<input name="end" type="number" min="1" max="10000" value="${s.end}" required></label><label>문항 수<input name="count" type="number" min="1" max="100" value="${s.count}" required></label><label>시간 (분)<input name="minutes" type="number" min="0.1" max="180" step="0.1" value="${s.minutes}" required></label><button class="remove-subject text-button" data-remove="${i}" type="button" aria-label="${i+1}번째 과목 설정 제외" ${i===0?'disabled':''}>✕</button></div>`;}
function renderSetup(){
  const stored=load('current');if(stored && ['ready','running','between'].includes(stored.phase))exam=stored;
  view='setup';nav();clearInterval(timer);
  const recover=exam && ['ready','running','between'].includes(exam.phase);
  app.className='setup-page';
  app.innerHTML=`<div class="hero"><div><span class="eyebrow">A LITTLE PRACTICE. A BETTER PACE.</span><h1>실전처럼 풀고,<br><span>나의 페이스를 찾으세요.</span></h1><p>내 PDF로 시작하는 모의 시험.<br>한 문제씩 확정하고, 풀이 시간을 남겨 보세요.</p></div><div class="hero-art" aria-hidden="true"><div class="orbit orbit-one"></div><div class="orbit orbit-two"></div><div class="pace-card"><span>YOUR NEXT PACE</span><strong>15:00</strong><div class="mini-bars"><i></i><i></i><i></i><i></i><i></i><i></i><i></i></div><small>20 questions · one step at a time</small></div><span class="floating-tag">✓ 준비되면 시작</span></div></div>
  ${recover?`<section class="resume-banner"><div><strong>이어서 볼 수 있는 시험이 있습니다.</strong><p>${e(exam.title)} · ${e(exam.sections[exam.sectionIndex].name)}${exam.phase==='running'?' · 제한시간이 계속 흐르고 있습니다.':''}</p></div><button id="resume-exam" class="primary">이어보기</button></section>`:''}
  <form id="setup-form"><div class="setup-grid"><div class="setup-main"><section class="panel"><div class="section-title"><h2><span class="step-dot">1</span> 시험과 PDF</h2><span class="subtle">서버 전송 없이 내 기기에서</span></div><label class="wide-label">시험 이름<input id="exam-title" maxlength="120" placeholder="예: 해커스 실전모의고사 1회" value="${e(config.title)}" required></label><label class="upload-area" for="pdf-file"><span class="file-icon">↥</span><strong id="pdf-file-name">${e(fileName || '내 PDF 선택')}</strong><span id="pdf-file-meta">${pdfInfo?`총 ${pdfInfo.count}페이지 · 페이지 범위를 아래에서 지정하세요`:'클릭해서 PDF를 선택하세요 · 최대 250MB'}</span><input id="pdf-file" type="file" accept="application/pdf,.pdf"></label><p class="subtle">문제집은 각자 이용 권한이 있는 파일을 선택해 주세요. 사이트에서 공유되지 않습니다.</p></section>
  <section class="panel"><div class="section-title"><h2><span class="step-dot">2</span> 과목별 시험 설정</h2><button id="add-subject" type="button" class="text-button">+ 과목 추가</button></div><p class="subtle">PDF의 실제 페이지 순서로 입력하세요. 인쇄된 책 쪽수와 다를 수 있습니다.</p><div id="subjects">${config.sections.map(subjectRow).join('')}</div><div class="setup-options"><label>사전 준비 화질<select id="quality"><option value="1050">표준 · 빠른 준비</option><option value="1450">선명 · 메모리 사용 증가</option></select></label><span class="subtle">선택한 페이지를 모두 준비한 뒤 타이머가 시작됩니다.</span></div></section>
  <section class="panel"><div class="section-title"><h2><span class="step-dot">3</span> 채점 방식</h2><button id="register-key" class="text-button" type="button">+ 정답표 등록</button></div><label class="wide-label">사용할 정답표<select id="key-select"><option value="">시험 종료 후 직접 정답 입력</option>${library.map(k=>`<option value="${e(k.id)}" ${selectedKey===k.id?'selected':''}>${e(k.title)} · ${k.sections.length}개 과목</option>`).join('')}</select></label><p class="subtle">등록한 정답표는 시험 중 화면에 표시하지 않습니다. 해설은 제공하지 않습니다.</p><div class="actions"><button id="import-config" type="button" class="secondary small">시험 설정 가져오기</button><button id="export-config" type="button" class="secondary small">시험 설정 내보내기</button><input id="config-file" type="file" accept="application/json,.json" hidden></div><p class="subtle">설정 파일에는 페이지 범위와 선택한 정답표가 들어갈 수 있습니다. PDF는 포함되지 않습니다.</p></section></div>
  <aside class="setup-aside"><div class="panel start-card"><span class="eyebrow">READY WHEN YOU ARE</span><h2>오늘의 연습을<br>시작해 볼까요?</h2><ul><li><span>✓</span>문제별 풀이 시간 기록</li><li><span>✓</span>확정한 답안은 변경 불가</li><li><span>✓</span>과목별 제한시간 자동 제출</li><li><span>✓</span>메모장 · 그림판 · 계산기</li></ul><div id="prepare-progress" hidden><progress max="100" value="0"></progress><p class="subtle"></p></div><button id="prepare-button" class="primary wide" type="submit">PDF 준비하기 <span>→</span></button><p class="subtle centered">준비 중에는 시험 시간이 흐르지 않습니다.</p><div id="setup-error" class="form-error" role="alert" hidden></div></div><div class="privacy-note"><span>◉</span><p><strong>기록은 내 브라우저에만.</strong><br>결과를 복사하거나 PDF로 저장해<br>원하는 곳에 직접 보관하세요.</p></div></aside></div></form><footer class="page-footer">페이스룸은 개인 연습 도구입니다. SKCT 공식 서비스와 관련이 없습니다.</footer>`;
  document.querySelector('#storage-warning').hidden=storageAvailable();
  app.querySelector('#pdf-file').onchange=async event=>{
    if(busy)return;config=currentConfig();selectedKey=app.querySelector('#key-select').value;
    const file=event.target.files[0];if(!file)return;busy=true;disableSetup(true);showSetupError('');
    try { pdfInfo=await openPDF(file);fileName=file.name;prepared=false;app.querySelector('#pdf-file-name').textContent=fileName;app.querySelector('#pdf-file-meta').textContent=`총 ${pdfInfo.count}페이지 · 준비 전 페이지 범위를 설정하세요`; }
    catch(err){pdfInfo=null;prepared=false;fileName='';showSetupError(err.message);}
    finally{busy=false;disableSetup(false);}
  };
  app.querySelector('#add-subject').onclick=()=>{config=currentConfig();if(config.sections.length>=8)return notify('과목은 최대 8개입니다.');selectedKey=app.querySelector('#key-select').value;config.sections.push({name:['언어이해','자료해석','창의수리','언어추리','수열추리'][config.sections.length]||`과목 ${config.sections.length+1}`,start:config.sections.at(-1).end+1,end:config.sections.at(-1).end+1,count:20,minutes:15,key:null});renderSetup();};
  app.querySelectorAll('[data-remove]').forEach(b=>b.onclick=()=>{config=currentConfig();config.sections.splice(Number(b.dataset.remove),1);renderSetup();});
  app.querySelector('#key-select').onchange=event=>selectedKey=event.target.value;
  app.querySelector('#register-key').onclick=()=>{config=currentConfig();openKeyDialog();};
  app.querySelector('#setup-form').onsubmit=async event=>{event.preventDefault();if(busy)return;showSetupError('');
    try { config=applyLibrary(validateConfig(currentConfig()));if(!pdfInfo)throw new Error('먼저 내 PDF를 선택해 주세요.');if(exam && ['ready','running','between'].includes(exam.phase) && !confirm('진행 중인 시험을 종료하고 새 시험을 준비할까요? 현재 시험은 결과 기록에 남깁니다.'))return;
      if(exam && ['ready','running','between'].includes(exam.phase)){finishAbandoned();}
      busy=true;disableSetup(true);app.querySelector('#prepare-progress').hidden=false;
      await preparePDF(config.sections,Number(app.querySelector('#quality').value),(n,total)=>{app.querySelector('progress').value=n/total*100;app.querySelector('#prepare-progress p').textContent=`${n} / ${total}페이지 준비 완료`;});
      prepared=true;exam=createExam(config,pdfInfo.hash);persist();pageNumber=exam.sections[0].start;renderExam();
    } catch(err){showSetupError(err.message);}finally{busy=false;if(view==='setup')disableSetup(false);}
  };
  app.querySelector('#resume-exam')?.addEventListener('click',()=>resumeExam());
  app.querySelector('#export-config').onclick=()=>{try{download('시험설정.json',JSON.stringify({version:1,...applyLibrary(validateConfig(currentConfig()))},null,2),'application/json');}catch(err){notify(err.message);}};
  app.querySelector('#import-config').onclick=()=>app.querySelector('#config-file').click();
  app.querySelector('#config-file').onchange=async event=>{try{const file=event.target.files[0];if(!file)return;if(file.size>1024*1024)throw new Error('설정 파일은 1MB 이하만 가능합니다.');const input=JSON.parse(await file.text());const imported=validateConfig(input);config={...imported,sections:imported.sections.map(s=>({...s,key:null}))};if(imported.sections.some(s=>s.key)){const key={id:crypto.randomUUID(),title:imported.title,sections:imported.sections.map(s=>({name:s.name,count:s.count,key:s.key}))};library.push(key);save('keys',library);selectedKey=key.id;}else selectedKey='';renderSetup();notify('시험 설정을 불러왔습니다. 각자의 PDF를 선택해 주세요.');}catch(err){notify(err.message);}};
}
function disableSetup(disabled){app.querySelectorAll('#setup-form input, #setup-form button, #setup-form select').forEach(el=>el.disabled=disabled);if(!disabled){app.querySelector('[data-remove="0"]').disabled=true;}}
function showSetupError(message){const box=app.querySelector('#setup-error');if(box){box.textContent=message;box.hidden=!message;}}
function finishAbandoned(){if(exam.phase==='running')submitSection(exam);while(exam.phase==='between'){const s=exam.sections[exam.sectionIndex];s.elapsed=0;s.endedAt=Date.now();if(exam.sectionIndex+1<exam.sections.length)exam.sectionIndex++;else exam.phase='finished';}if(exam.phase==='ready')exam.phase='finished';exam.abandoned=true;rememberResult(exam);persist();}
async function resumeExam(){
  if(busy)return;
  if(expire(exam)){persist();if(exam.phase==='finished'){rememberResult(exam);return renderResult();}}
  if(prepared && pdfInfo?.hash===exam.pdfHash){pageNumber=exam.sections[exam.sectionIndex].start;return renderExam();}
  if(!pdfInfo)return notify('응시했던 PDF를 먼저 선택하고 이어보기를 눌러 주세요.');
  if(pdfInfo.hash!==exam.pdfHash)return notify('응시했던 PDF와 다른 파일입니다. 같은 PDF를 선택해 주세요.');
  busy=true;disableSetup(true);app.querySelector('#prepare-progress').hidden=false;
  try{await preparePDF(exam.sections,1050,(n,total)=>{app.querySelector('progress').value=n/total*100;app.querySelector('#prepare-progress p').textContent=`${n} / ${total}페이지 복구 중 · 응시 시간은 계속 흐릅니다`;});prepared=true;expire(exam);persist();if(exam.phase==='finished'){rememberResult(exam);renderResult();}else{pageNumber=exam.sections[exam.sectionIndex].start;renderExam();}}
  catch(err){showSetupError(err.message);}finally{busy=false;if(view==='setup')disableSetup(false);}
}
function renderExam(){
  view='exam';nav();clearInterval(timer);resultFilter='all';const s=exam.sections[exam.sectionIndex], running=exam.phase==='running';
  app.className='exam-page';
  app.innerHTML=`<div class="exam-top"><div><span class="eyebrow">${e(exam.title)}</span><h1>${e(s.name)} <small>${exam.sectionIndex+1} / ${exam.sections.length}과목</small></h1></div><div class="exam-status"><span class="pill">${running?'실전 응시 중':'시작 전 · 준비 완료'}</span><span>${s.count}문제 · ${s.minutes}분</span></div></div><div class="exam-layout"><section class="pdf-panel"><div class="pdf-toolbar"><span class="subtle">PDF 페이지 <strong id="page-label"></strong></span><div class="actions"><button id="prev-page" class="icon-button" aria-label="이전 PDF 페이지">←</button><button id="next-page" class="icon-button" aria-label="다음 PDF 페이지">→</button><label class="zoom-label">배율<select id="pdf-zoom"><option value="100">100%</option><option value="125">125%</option><option value="150">150%</option><option value="200">200%</option></select></label></div></div><div id="pdf-page" class="pdf-page"></div><div class="pdf-footnote">PDF를 앞뒤로 넘겨도 현재 답안 번호는 바뀌지 않습니다.</div></section><aside class="exam-sidebar"><section class="panel answer-panel"><div class="timer-label"><span>과목 남은 시간</span><span class="live-dot"></span></div><div id="remaining-time" class="timer">${formatTime(s.minutes*60000)}</div><div class="timer-track"><div id="timer-fill"></div></div>${running?`<div class="current-question"><span>현재 문제</span><strong>${String(exam.questionIndex+1).padStart(2,'0')}<small> / ${s.count}</small></strong><span class="question-time">이 문제 <b id="question-time">00:00</b></span></div><div class="answer-options" role="group" aria-label="${exam.questionIndex+1}번 답안 선택">${[1,2,3,4,5].map(a=>`<button data-answer="${a}" aria-pressed="${exam.selection===a}" class="${exam.selection===a?'selected':''}">${a}</button>`).join('')}</div><button id="confirm-answer" class="primary wide" ${exam.selection==null?'disabled':''}>확정하고 ${exam.questionIndex+1===s.count?'과목 종료':'다음'} →</button><button id="skip-answer" class="secondary wide">건너뛰기</button><p class="subtle centered">확정·건너뛴 답안은 다시 입력할 수 없습니다.</p><div class="omr-strip" aria-label="답안 진행 상황">${s.items.map((item,i)=>`<span class="${i===exam.questionIndex?'current':item.answer!=null?'done':item.status!=='unreached'?'skipped':''}" title="${i+1}번 ${i===exam.questionIndex?'현재 문제':item.answer!=null?'확정':item.status!=='unreached'?'미응답':'미도달'}">${i+1}</span>`).join('')}</div><button id="submit-section" class="text-button wide">현재 과목 조기 제출</button>`:`<div class="ready-message"><span>✓</span><h2>${exam.phase==='between'?'이전 과목이 종료되었습니다.':'모든 페이지 준비 완료'}</h2><p>답을 확정하면 돌아갈 수 없습니다.<br>시작 버튼을 누르면 제한시간이 흐릅니다.</p></div><button id="start-section" class="primary wide">${e(s.name)} 시작 →</button>`}</section><section class="panel tool-panel">${toolsMarkup()}</section></aside></div>`;
  if(pageNumber<s.start||pageNumber>s.end)pageNumber=s.start;showPage();
  app.querySelector('#prev-page').onclick=()=>{if(pageNumber>s.start){pageNumber--;showPage();}};app.querySelector('#next-page').onclick=()=>{if(pageNumber<s.end){pageNumber++;showPage();}};
  app.querySelector('#pdf-zoom').value=String(zoom);app.querySelector('#pdf-zoom').onchange=event=>{zoom=Number(event.target.value);showPage();};
  app.querySelector('#start-section')?.addEventListener('click',()=>{startSection(exam);persist();renderExam();});
  app.querySelectorAll('[data-answer]').forEach(b=>b.onclick=()=>{const changed=chooseAnswer(exam,Number(b.dataset.answer));persist();if(!changed){afterChange();return;}app.querySelectorAll('[data-answer]').forEach(x=>{x.classList.toggle('selected',x===b);x.setAttribute('aria-pressed',String(x===b));});app.querySelector('#confirm-answer').disabled=false;});
  const expected=exam.questionIndex;
  function proceed(skip){if(Date.now()-lastAction<300)return;lastAction=Date.now();if(skip&&!confirm('답을 입력하지 않고 넘어갈까요? 이 문제에는 돌아갈 수 없습니다.'))return;advance(exam,skip,Date.now(),expected);persist();afterChange();}
  app.querySelector('#confirm-answer')?.addEventListener('click',()=>proceed(false));app.querySelector('#skip-answer')?.addEventListener('click',()=>proceed(true));
  app.querySelector('#submit-section')?.addEventListener('click',()=>{if(confirm('현재 과목을 제출할까요? 선택 중인 답은 제출하고, 남은 문제는 미도달로 기록합니다.')){submitSection(exam);persist();afterChange();}});
  mountTools(app.querySelector('.tool-panel'),exam,persist);tick();timer=setInterval(tick,200);
}
function showPage(){const s=exam.sections[exam.sectionIndex],image=pageImage(pageNumber),box=app.querySelector('#pdf-page');if(!image)return;box.replaceChildren(image);image.style.width=zoom+'%';app.querySelector('#page-label').textContent=`${pageNumber} / 범위 ${s.start}–${s.end}`;app.querySelector('#prev-page').disabled=pageNumber<=s.start;app.querySelector('#next-page').disabled=pageNumber>=s.end;box.scrollTop=0;box.scrollLeft=0;}
function tick(){if(!exam||view!=='exam')return;if(expire(exam)){persist();notify('제한시간이 끝나 현재 과목이 자동 제출되었습니다.');afterChange();return;}if(exam.phase!=='running')return;const now=Date.now(),left=Math.max(0,exam.deadline-now),s=exam.sections[exam.sectionIndex];app.querySelector('#remaining-time').textContent=formatTime(Math.ceil(left/1000)*1000);app.querySelector('#remaining-time').classList.toggle('urgent',left<60000);app.querySelector('#question-time').textContent=formatTime(now-exam.questionStartedAt);app.querySelector('#timer-fill').style.width=100*left/(s.minutes*60000)+'%';}
function afterChange(){if(exam.phase==='finished'){rememberResult(exam);renderResult();}else renderExam();}
function renderResult(){view='result';nav();clearInterval(timer);app.className='result-page';app.innerHTML=reportMarkup(exam);app.querySelector('#reflection').value=exam.reflection||'';app.querySelector('#reflection').oninput=event=>{exam.reflection=event.target.value;persist();rememberResult(exam);app.querySelector('.reflection .print-only').textContent=exam.reflection||'작성한 메모가 없습니다.';};
  app.querySelector('#grade-form').onsubmit=event=>{event.preventDefault();try{const keys=[...app.querySelectorAll('[data-grade]')].map((input,i)=>input.value.trim()?parseKey(input.value,exam.sections[i].count):null);exam.sections.forEach((s,i)=>s.key=keys[i]);persist();rememberResult(exam);renderResult();notify('채점 결과를 갱신했습니다.');}catch(err){notify(err.message);}};
  app.querySelector('#save-key').onclick=()=>{try{const sections=[...app.querySelectorAll('[data-grade]')].map((input,i)=>({name:exam.sections[i].name,count:exam.sections[i].count,key:parseKey(input.value,exam.sections[i].count)}));const key={id:crypto.randomUUID(),title:exam.title,sections};library.push(key);save('keys',library);notify('정답표를 내 브라우저에 저장했습니다.');}catch(err){notify(err.message);}};
  app.querySelector('#copy-result').onclick=async()=>{const {text,html}=copyContent(exam);try{if(globalThis.ClipboardItem&&navigator.clipboard.write){await navigator.clipboard.write([new ClipboardItem({'text/plain':new Blob([text],{type:'text/plain'}),'text/html':new Blob([html],{type:'text/html'})})]);}else await navigator.clipboard.writeText(text);notify('결과를 복사했습니다. 노션 등에 붙여넣으세요.');}catch{const d=document.createElement('dialog');d.innerHTML='<h2>결과 직접 복사</h2><p>아래 내용을 전체 선택해 복사하세요.</p><textarea rows="15" aria-label="복사할 결과"></textarea><button class="primary">닫기</button>';document.body.append(d);d.querySelector('textarea').value=text;d.querySelector('button').onclick=()=>d.close();d.onclose=()=>d.remove();d.showModal();d.querySelector('textarea').select();}};
  app.querySelector('#download-csv').onclick=()=>download(exam.title+'-결과.csv',csvContent(exam),'text/csv;charset=utf-8');
  app.querySelector('#print-result').onclick=()=>{applyFilter('all');window.print();};
  app.querySelectorAll('[data-filter]').forEach(b=>b.onclick=()=>applyFilter(b.dataset.filter));applyFilter(resultFilter);
}
function applyFilter(filter){resultFilter=filter;let shown=0;app.querySelectorAll('[data-filter]').forEach(b=>b.classList.toggle('active',b.dataset.filter===filter));app.querySelectorAll('.question-card').forEach(card=>{const hide=filter!=='all'&&card.dataset[filter]!=='true';card.hidden=hide;shown+=!hide;});app.querySelector('#filter-empty').hidden=shown>0;}
function renderHistory(){view='history';nav();clearInterval(timer);const results=savedResults();app.className='history-page';app.innerHTML=`<div class="result-heading"><div><span class="eyebrow">MY PRACTICE LOG</span><h1>내 응시 기록</h1><p class="subtle">이 브라우저에서 남긴 연습을 다시 확인하세요.</p></div><button id="new-exam" class="primary">새 시험 준비 →</button></div>${results.length?`<div class="history-list">${results.map(r=>{const t=totals(r);return `<button class="history-card" data-result="${e(r.id)}"><span class="history-icon">↗</span><span><strong>${e(r.title)}</strong><small>${new Date(r.createdAt).toLocaleString('ko-KR')} · ${r.sections.length}개 과목 ${r.abandoned?'· 중단한 시험':''}</small></span><span class="history-score">${t.graded?t.correct+' / '+t.graded:'미채점'}<small>${formatTime(t.elapsed)}</small></span></button>`;}).join('')}</div>`:'<section class="panel empty-state"><span class="empty-icon">◷</span><h2>첫 연습을 기다리고 있어요.</h2><p>시험을 마치면 이곳에서 결과를 다시 볼 수 있습니다.</p></section>'}<p class="subtle">기록은 서버에 저장되지 않습니다. 중요한 결과는 복사하거나 PDF로 보관하세요.</p>`;app.querySelector('#new-exam').onclick=renderSetup;app.querySelectorAll('[data-result]').forEach(b=>b.onclick=()=>{exam=results.find(r=>r.id===b.dataset.result);resultFilter='all';renderResult();});}
function openKeyDialog(){const d=document.createElement('dialog');d.innerHTML=`<span class="eyebrow">ANSWER KEY</span><h2>나만의 정답표 등록</h2><p class="subtle">현재 설정된 과목 순서로 입력하세요. 시험 중에는 표시되지 않습니다.</p><form id="key-form"><label class="wide-label">정답표 이름<input id="key-title" maxlength="120" value="${e(config.title)}" required></label>${config.sections.map((s,i)=>`<label class="wide-label">${e(s.name)} · ${s.count}문제<textarea data-key="${i}" rows="2" placeholder="1 2 3 4 5 …" required></textarea></label>`).join('')}<p class="form-error" id="key-error" hidden></p><div class="actions"><button type="button" class="secondary" id="cancel-key">취소</button><button class="primary">저장</button></div></form>`;document.body.append(d);d.querySelector('#cancel-key').onclick=()=>d.close();d.onclose=()=>d.remove();d.querySelector('form').onsubmit=event=>{event.preventDefault();try{const sections=config.sections.map((s,i)=>({name:s.name,count:s.count,key:parseKey(d.querySelector(`[data-key="${i}"]`).value,s.count)}));const key={id:crypto.randomUUID(),title:d.querySelector('#key-title').value.trim(),sections};if(!key.title)throw new Error('정답표 이름을 입력해 주세요.');library.push(key);save('keys',library);selectedKey=key.id;d.close();renderSetup();notify('정답표를 저장했습니다.');}catch(err){d.querySelector('#key-error').textContent=err.message;d.querySelector('#key-error').hidden=false;}};d.showModal();}
function download(name,content,type){const blob=new Blob([content],{type}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name.replace(/[\\/:*?"<>|]/g,'_');a.click();setTimeout(()=>URL.revokeObjectURL(url),10000);}
document.querySelector('#nav-setup').onclick=()=>{if(busy)return;if(view==='exam'&&exam.phase==='running')return notify('응시 중에는 시험 화면을 유지합니다. 과목을 제출한 뒤 이동할 수 있습니다.');renderSetup();};
document.querySelector('#nav-history').onclick=()=>{if(busy)return;if(exam?.phase==='running')return notify('응시 중에는 기록 화면으로 이동할 수 없습니다.');renderHistory();};
document.querySelector('#nav-help').onclick=()=>document.querySelector('#help-dialog').showModal();document.querySelector('.close-dialog').onclick=()=>document.querySelector('#help-dialog').close();
document.querySelector('.brand').onclick=event=>{event.preventDefault();if(!busy&&exam?.phase!=='running')renderSetup();};
document.addEventListener('visibilitychange',()=>{if(locked&&exam?.phase==='running'&&expire(exam)){persist();if(view==='exam')afterChange();}});
window.addEventListener('beforeunload',event=>{if(exam?.phase==='running'){persist();event.preventDefault();event.returnValue='';}});
window.addEventListener('pagehide',()=>releaseLock?.());
